<?
$payload = stdClass::__set_state(array(
   'ref' => 'refs/heads/test',
   'before' => '0000000000000000000000000000000000000000',
   'after' => '47b752ba6f9e41a74fe48f6c83f839b8da601401',
   'created' => true,
   'deleted' => false,
   'forced' => false,
   'base_ref' => NULL,
   'compare' => 'https://github.com/lilliputten/simple-test/commit/47b752ba6f9e',
   'commits' =>
  array (
    0 =>
    stdClass::__set_state(array(
       'id' => '47b752ba6f9e41a74fe48f6c83f839b8da601401',
       'tree_id' => '3058a231c20e051ca1e4581b35ee35ed90873e5c',
       'distinct' => true,
       'message' => 'Webhook test',
       'timestamp' => '2019-01-25T19:54:16+03:00',
       'url' => 'https://github.com/lilliputten/simple-test/commit/47b752ba6f9e41a74fe48f6c83f839b8da601401',
       'author' =>
      stdClass::__set_state(array(
         'name' => 'lilliputten',
         'email' => 'lilliputten@yandex.ru',
         'username' => 'lilliputten',
      )),
       'committer' =>
      stdClass::__set_state(array(
         'name' => 'lilliputten',
         'email' => 'lilliputten@yandex.ru',
         'username' => 'lilliputten',
      )),
       'added' =>
      array (
        0 => 'bitbucket-payload.php',
        1 => 'github-payload.php',
      ),
       'removed' =>
      array (
      ),
       'modified' =>
      array (
        0 => 'test',
      ),
    )),
  ),
   'head_commit' =>
  stdClass::__set_state(array(
     'id' => '47b752ba6f9e41a74fe48f6c83f839b8da601401',
     'tree_id' => '3058a231c20e051ca1e4581b35ee35ed90873e5c',
     'distinct' => true,
     'message' => 'Webhook test',
     'timestamp' => '2019-01-25T19:54:16+03:00',
     'url' => 'https://github.com/lilliputten/simple-test/commit/47b752ba6f9e41a74fe48f6c83f839b8da601401',
     'author' =>
    stdClass::__set_state(array(
       'name' => 'lilliputten',
       'email' => 'lilliputten@yandex.ru',
       'username' => 'lilliputten',
    )),
     'committer' =>
    stdClass::__set_state(array(
       'name' => 'lilliputten',
       'email' => 'lilliputten@yandex.ru',
       'username' => 'lilliputten',
    )),
     'added' =>
    array (
      0 => 'bitbucket-payload.php',
      1 => 'github-payload.php',
    ),
     'removed' =>
    array (
    ),
     'modified' =>
    array (
      0 => 'test',
    ),
  )),
   'repository' =>
  stdClass::__set_state(array(
     'id' => 167566751,
     'node_id' => 'MDEwOlJlcG9zaXRvcnkxNjc1NjY3NTE=',
     'name' => 'simple-test',
     'full_name' => 'lilliputten/simple-test',
     'private' => false,
     'owner' =>
    stdClass::__set_state(array(
       'name' => 'lilliputten',
       'email' => 'lilliputten@yandex.ru',
       'login' => 'lilliputten',
       'id' => 6855837,
       'node_id' => 'MDQ6VXNlcjY4NTU4Mzc=',
       'avatar_url' => 'https://avatars2.githubusercontent.com/u/6855837?v=4',
       'gravatar_id' => '',
       'url' => 'https://api.github.com/users/lilliputten',
       'html_url' => 'https://github.com/lilliputten',
       'followers_url' => 'https://api.github.com/users/lilliputten/followers',
       'following_url' => 'https://api.github.com/users/lilliputten/following{/other_user}',
       'gists_url' => 'https://api.github.com/users/lilliputten/gists{/gist_id}',
       'starred_url' => 'https://api.github.com/users/lilliputten/starred{/owner}{/repo}',
       'subscriptions_url' => 'https://api.github.com/users/lilliputten/subscriptions',
       'organizations_url' => 'https://api.github.com/users/lilliputten/orgs',
       'repos_url' => 'https://api.github.com/users/lilliputten/repos',
       'events_url' => 'https://api.github.com/users/lilliputten/events{/privacy}',
       'received_events_url' => 'https://api.github.com/users/lilliputten/received_events',
       'type' => 'User',
       'site_admin' => false,
    )),
     'html_url' => 'https://github.com/lilliputten/simple-test',
     'description' => 'Minimal www root test bundle',
     'fork' => false,
     'url' => 'https://github.com/lilliputten/simple-test',
     'forks_url' => 'https://api.github.com/repos/lilliputten/simple-test/forks',
     'keys_url' => 'https://api.github.com/repos/lilliputten/simple-test/keys{/key_id}',
     'collaborators_url' => 'https://api.github.com/repos/lilliputten/simple-test/collaborators{/collaborator}',
     'teams_url' => 'https://api.github.com/repos/lilliputten/simple-test/teams',
     'hooks_url' => 'https://api.github.com/repos/lilliputten/simple-test/hooks',
     'issue_events_url' => 'https://api.github.com/repos/lilliputten/simple-test/issues/events{/number}',
     'events_url' => 'https://api.github.com/repos/lilliputten/simple-test/events',
     'assignees_url' => 'https://api.github.com/repos/lilliputten/simple-test/assignees{/user}',
     'branches_url' => 'https://api.github.com/repos/lilliputten/simple-test/branches{/branch}',
     'tags_url' => 'https://api.github.com/repos/lilliputten/simple-test/tags',
     'blobs_url' => 'https://api.github.com/repos/lilliputten/simple-test/git/blobs{/sha}',
     'git_tags_url' => 'https://api.github.com/repos/lilliputten/simple-test/git/tags{/sha}',
     'git_refs_url' => 'https://api.github.com/repos/lilliputten/simple-test/git/refs{/sha}',
     'trees_url' => 'https://api.github.com/repos/lilliputten/simple-test/git/trees{/sha}',
     'statuses_url' => 'https://api.github.com/repos/lilliputten/simple-test/statuses/{sha}',
     'languages_url' => 'https://api.github.com/repos/lilliputten/simple-test/languages',
     'stargazers_url' => 'https://api.github.com/repos/lilliputten/simple-test/stargazers',
     'contributors_url' => 'https://api.github.com/repos/lilliputten/simple-test/contributors',
     'subscribers_url' => 'https://api.github.com/repos/lilliputten/simple-test/subscribers',
     'subscription_url' => 'https://api.github.com/repos/lilliputten/simple-test/subscription',
     'commits_url' => 'https://api.github.com/repos/lilliputten/simple-test/commits{/sha}',
     'git_commits_url' => 'https://api.github.com/repos/lilliputten/simple-test/git/commits{/sha}',
     'comments_url' => 'https://api.github.com/repos/lilliputten/simple-test/comments{/number}',
     'issue_comment_url' => 'https://api.github.com/repos/lilliputten/simple-test/issues/comments{/number}',
     'contents_url' => 'https://api.github.com/repos/lilliputten/simple-test/contents/{+path}',
     'compare_url' => 'https://api.github.com/repos/lilliputten/simple-test/compare/{base}...{head}',
     'merges_url' => 'https://api.github.com/repos/lilliputten/simple-test/merges',
     'archive_url' => 'https://api.github.com/repos/lilliputten/simple-test/{archive_format}{/ref}',
     'downloads_url' => 'https://api.github.com/repos/lilliputten/simple-test/downloads',
     'issues_url' => 'https://api.github.com/repos/lilliputten/simple-test/issues{/number}',
     'pulls_url' => 'https://api.github.com/repos/lilliputten/simple-test/pulls{/number}',
     'milestones_url' => 'https://api.github.com/repos/lilliputten/simple-test/milestones{/number}',
     'notifications_url' => 'https://api.github.com/repos/lilliputten/simple-test/notifications{?since,all,participating}',
     'labels_url' => 'https://api.github.com/repos/lilliputten/simple-test/labels{/name}',
     'releases_url' => 'https://api.github.com/repos/lilliputten/simple-test/releases{/id}',
     'deployments_url' => 'https://api.github.com/repos/lilliputten/simple-test/deployments',
     'created_at' => 1548429283,
     'updated_at' => '2019-01-25T16:44:00Z',
     'pushed_at' => 1548435268,
     'git_url' => 'git://github.com/lilliputten/simple-test.git',
     'ssh_url' => 'git@github.com:lilliputten/simple-test.git',
     'clone_url' => 'https://github.com/lilliputten/simple-test.git',
     'svn_url' => 'https://github.com/lilliputten/simple-test',
     'homepage' => NULL,
     'size' => 2,
     'stargazers_count' => 0,
     'watchers_count' => 0,
     'language' => 'PHP',
     'has_issues' => true,
     'has_projects' => true,
     'has_downloads' => true,
     'has_wiki' => true,
     'has_pages' => false,
     'forks_count' => 0,
     'mirror_url' => NULL,
     'archived' => false,
     'open_issues_count' => 0,
     'license' => NULL,
     'forks' => 0,
     'open_issues' => 0,
     'watchers' => 0,
     'default_branch' => 'master',
     'stargazers' => 0,
     'master_branch' => 'master',
  )),
   'pusher' =>
  stdClass::__set_state(array(
     'name' => 'lilliputten',
     'email' => 'lilliputten@yandex.ru',
  )),
   'sender' =>
  stdClass::__set_state(array(
     'login' => 'lilliputten',
     'id' => 6855837,
     'node_id' => 'MDQ6VXNlcjY4NTU4Mzc=',
     'avatar_url' => 'https://avatars2.githubusercontent.com/u/6855837?v=4',
     'gravatar_id' => '',
     'url' => 'https://api.github.com/users/lilliputten',
     'html_url' => 'https://github.com/lilliputten',
     'followers_url' => 'https://api.github.com/users/lilliputten/followers',
     'following_url' => 'https://api.github.com/users/lilliputten/following{/other_user}',
     'gists_url' => 'https://api.github.com/users/lilliputten/gists{/gist_id}',
     'starred_url' => 'https://api.github.com/users/lilliputten/starred{/owner}{/repo}',
     'subscriptions_url' => 'https://api.github.com/users/lilliputten/subscriptions',
     'organizations_url' => 'https://api.github.com/users/lilliputten/orgs',
     'repos_url' => 'https://api.github.com/users/lilliputten/repos',
     'events_url' => 'https://api.github.com/users/lilliputten/events{/privacy}',
     'received_events_url' => 'https://api.github.com/users/lilliputten/received_events',
     'type' => 'User',
     'site_admin' => false,
  )),
));
